// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace InfoSecLab.Models;

[Table("USER")]
[Index("UserEmail", Name = "USER_EMAIL_UNIQUE", IsUnique = true)]
[Index("UserId", Name = "USER_ID_UNIQUE", IsUnique = true)]
public partial class User
{
    [Key]
    [Column("USER_ID")]
    public uint UserId { get; set; }

    [Column("USER_EMAIL")]
    public string UserEmail { get; set; } = null!;

    [Column("USER_PWD_HASH")]
    [StringLength(256)]
    public string UserPwdHash { get; set; } = null!;

    [InverseProperty("User")]
    public virtual ICollection<UserLogin> UserLogins { get; set; } = new List<UserLogin>();
}